[raspberry]
dns-01 ansible_host=192.168.0.110
node-01 ansible_host=192.168.0.111
node-02 ansible_host=192.168.0.112

[unbound]
dns-01

[pihole]
node-01

[raspberry_nodes]
node-01
node-02


[kubernetes:children]
control_plane
workers

[control_plane]
k8s-cp-01 ansible_host=192.168.0.130

[workers]
k8s-worker-01 ansible_host=192.168.0.131
k8s-worker-02 ansible_host=192.168.0.132