blank_issues_enabled: false

contact_links:
  - name: Project Documentation
    url: https://github.com/adenntumba/enterprise-platform-lab
    about: Please read the project documentation before opening an issue.