galaxy_info:

  author: Adenn Tumba

  description: Base Linux configuration for Enterprise Platform Lab

  company: Enterprise Platform Lab

  license: MIT

  min_ansible_version: "2.15"

dependencies: []