---
# containerd role defaults

containerd_package: containerd

containerd_service: containerd

containerd_config_file: /etc/containerd/config.toml

containerd_systemd_cgroup: true

containerd_cni_bin_dir: /opt/cni/bin
