---
- name: Prepare Kubernetes nodes
  hosts: kubernetes
  become: true

  roles:
    - role: base/linux
    - role: kubernetes/common
    - role: kubernetes/containerd
    - role: kubernetes/packages

- name: Configure Kubernetes control plane
  hosts: control_plane
  become: true

  roles:
    - role: kubernetes/control_plane

- name: Configure Kubernetes workers
  hosts: workers
  become: true

  roles:
    - role: kubernetes/worker

- name: Deploy Kubernetes CNI
  hosts: control_plane
  become: true

  roles:
    - role: kubernetes/cni

- name: Configure Kubernetes internal DNS
  hosts: control_plane
  become: true

  roles:
    - role: kubernetes/dns